[theme]

primaryColor = "#E694FF"

# Background color
backgroundColor = "#00171B"

# Sidebar Background color
secondaryBackgroundColor = "#00100"

# Alt text colot
textColor = "#FFF"
font = "sans serif"